language: python
python:
  - "2.7"
  - "3.4"
  - "3.6"
services:
  - postgresql
addons:
  postgresql: "9.4"
  apt:
    sources:
      - sourceline: 'ppa:jonathonf/ffmpeg-3'
    packages: 
      - ffmpeg
install: 
  - "pip install -r requirements.txt"
before_script:
  - psql -c 'create database zoudb;' -U postgres
  - mkdir /home/travis/build/cgwire/zou/previews
env:
  - DEBUG=1 MAIL_DEBUG=1 FLASK_APP=zou.app PREVIEW_FOLDER=/home/travis/build/cgwire/zou/previews
script: py.test
